/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DisagreeableAutomationArtifactsV12 = DisagreeableAutomationArtifactsV121 &
  DisagreeableAutomationArtifactsV122;
export type DisagreeableAutomationArtifactsV121 = {
  [k: string]: unknown;
};

export interface DisagreeableAutomationArtifactsV122 {
  version: "1.2";
  mode: "standard" | "builder" | "chief_of_staff";
  /**
   * True only if the workflow can be explained, challenged, and reversed/stopped in practice.
   */
  deployable: boolean;
  /**
   * Required when deployable=false; list exactly what is missing.
   */
  missing_requirements?: string[];
  /**
   * Optional fields to keep artifacts living and reviewable over time.
   */
  lifecycle?: {
    last_reviewed_date: string;
    known_gaps?: string[];
    /**
     * Events that force re-evaluation (e.g., incident severity, threshold breach).
     */
    incident_triggers_for_re_review?: string[];
    artifact_owner?: string;
  };
  /**
   * Optional mapping for governance and compliance programs.
   */
  regulatory_alignment?: {
    regulatory_category?: string;
    compliance_frameworks?: string[];
    required_documentation?: string[];
  };
  /**
   * Optional: represent cross-workflow dependencies and cascade behavior in multi-agent systems.
   */
  workflow_dependencies?: {
    upstream_dependencies?: string[];
    downstream_impacts?: string[];
    /**
     * What happens if upstream is contested/reversed (e.g., halt downstream, compensate, re-run).
     */
    cascade_behavior?: string;
  };
  authority_boundary: {
    scope: string;
    /**
     * @minItems 1
     */
    allowed_actions: [string, ...string[]];
    /**
     * @minItems 1
     */
    forbidden_actions: [string, ...string[]];
    /**
     * Human-readable summary of the largest action allowed without escalation.
     */
    maximum_impact: string;
    escalation_trigger: string;
    /**
     * Machine-checkable thresholds and blast-radius limits.
     */
    quantified_limits: {
      money_limit?: {
        currency: string;
        amount: number;
      };
      /**
       * Max number of records/entities affected in a single run without escalation.
       */
      record_limit: number;
      /**
       * Optional: limit applied per time window (e.g., per hour/day).
       */
      time_window_seconds?: number;
      /**
       * Highest data sensitivity level the workflow is allowed to touch without escalation.
       */
      data_sensitivity: "public" | "internal" | "confidential" | "restricted";
      /**
       * Systems the agent is allowed to act within (names/identifiers).
       */
      system_scope?: string[];
      /**
       * How impact is measured for enforcement (e.g., 'downstream_api_calls', 'affected_user_accounts', 'modified_db_rows').
       */
      blast_radius_metric: string;
    };
  };
  ambiguity_handling: {
    /**
     * @minItems 1
     */
    what_counts_as_ambiguous: [string, ...string[]];
    routing_choice:
      | "tighten_rules"
      | "request_more_evidence"
      | "human_decision"
      | "safe_defer"
      | "human_now_then_learn_and_tighten";
    why_this_placement: string;
    what_happens_while_waiting: string;
    /**
     * Required when routing_choice=human_now_then_learn_and_tighten.
     */
    learning_plan?: {
      pattern_to_capture: string;
      rule_or_classifier_target: string;
      review_cycle: string;
    };
  };
  contest_path: {
    /**
     * @minItems 1
     */
    who_can_contest: [string, ...string[]];
    how_to_contest: string;
    /**
     * Human-readable conditions that change the outcome.
     *
     * @minItems 1
     */
    what_changes_the_result: [string, ...string[]];
    /**
     * Structured evidence types to enable machine-checkable contestation when possible.
     *
     * @minItems 1
     */
    evidence_requirements: [
      {
        type: "document_upload" | "human_attestation" | "system_verification" | "manual_review_required";
        required_fields?: string[];
        from_role?: string;
        api_endpoint?: string;
        notes?: string;
      },
      ...{
        type: "document_upload" | "human_attestation" | "system_verification" | "manual_review_required";
        required_fields?: string[];
        from_role?: string;
        api_endpoint?: string;
        notes?: string;
      }[]
    ];
    /**
     * Target response time (e.g., '2 hours', '1 business day').
     */
    time_to_response: string;
    during_contest_behavior: "paused" | "held_safe_mode" | "partial_reversible" | "continue_with_guardrails";
    sla_consequences: {
      on_breach: "auto_reverse" | "auto_pause" | "escalate_only" | "continue_with_guardrails";
      escalate_to: string;
    };
  };
  reversibility_plan: {
    safe_stop: string;
    /**
     * @minItems 1
     */
    commit_points: [
      {
        name: string;
        what_commits_here: string;
        approval_required: boolean;
      },
      ...{
        name: string;
        what_commits_here: string;
        approval_required: boolean;
      }[]
    ];
    undo_strategy: {
      type: "direct_rollback" | "compensation" | "mixed";
      details: string;
    };
    /**
     * Prefer measurable guardrails where possible.
     *
     * @minItems 1
     */
    runaway_guardrails: [
      (
        | string
        | {
            type: "rate_limit" | "budget_cap" | "failure_threshold" | "blast_radius_cap" | "time_box";
            max_actions_per_minute?: number;
            max_spend_per_day?: number;
            max_consecutive_errors?: number;
            max_blast_radius?: number;
            max_runtime_seconds?: number;
            notes?: string;
          }
      ),
      ...(
        | string
        | {
            type: "rate_limit" | "budget_cap" | "failure_threshold" | "blast_radius_cap" | "time_box";
            max_actions_per_minute?: number;
            max_spend_per_day?: number;
            max_consecutive_errors?: number;
            max_blast_radius?: number;
            max_runtime_seconds?: number;
            notes?: string;
          }
      )[]
    ];
    human_stop_authority: {
      who: string;
      how: string;
    };
    irreversible_actions: string[];
    /**
     * @minItems 1
     */
    partial_action_states: [
      {
        state_name: string;
        what_is_done: string;
        what_is_reversible: string;
        what_requires_compensation: string;
      },
      ...{
        state_name: string;
        what_is_done: string;
        what_is_reversible: string;
        what_requires_compensation: string;
      }[]
    ];
  };
  decision_receipt: {
    plain_language: {
      what_happened: string;
      why: string;
      what_it_relied_on: string;
      who_or_what_approved: string;
      how_to_challenge: string;
      how_to_undo_or_stop: string;
      who_owns_outcome: string;
    };
    machine_readable: {
      decision_id: string;
      timestamp: string;
      decision: string;
      action: string;
      /**
       * @minItems 1
       */
      reason_codes: [string, ...string[]];
      inputs_summary: string;
      policy_reference: string;
      approval: {
        type:
          | "rule_based"
          | "human_approved"
          | "human_rejected"
          | "not_required"
          | "auto_approved_with_conditions"
          | "time_based_approval"
          | "delegated_approval";
        by: string;
        conditions?: string;
        expires_at?: string;
        delegated_system?: string;
      };
      contest_reference: string;
      undo_reference: string;
      owner_reference: string;
      retention_policy: {
        /**
         * e.g., '90d', '7y'
         */
        duration: string;
        /**
         * e.g., 'policy', 'regulatory', 'contract'
         */
        basis: string;
      };
      /**
       * Where receipts can be queried (endpoint, table, index, or internal service name).
       */
      discovery_api: string;
      /**
       * Preferred bulk export format for audits.
       */
      export_format: "jsonl" | "csv" | "parquet" | "pdf_bundle" | "custom";
    };
  };
  ownership_and_escalation: {
    accountable_owner: string;
    escalation_rule: string;
    on_call_expectation: string;
    audit_cadence: string;
    handoff_protocol: {
      rotation_model: string;
      /**
       * @minItems 1
       */
      handoff_steps: [string, ...string[]];
      where_recorded: string;
    };
  };
  /**
   * Optional: runtime instrumentation and feedback loops that keep governance real.
   */
  observability_and_feedback?: {
    /**
     * @minItems 3
     */
    signals: [string, string, string, ...string[]];
    dashboards_or_logs: string;
    /**
     * @minItems 1
     */
    feedback_routes: [string, ...string[]];
    /**
     * @minItems 1
     */
    review_triggers: [string, ...string[]];
  };
  implementation_notes?: {
    /**
     * @minItems 1
     */
    inputs: [string, ...string[]];
    /**
     * @minItems 1
     */
    outputs: [string, ...string[]];
    where_approvals_live: string;
    where_stop_and_undo_live: string;
    /**
     * @minItems 3
     */
    runtime_receipt_fields: [string, string, string, ...string[]];
    /**
     * @minItems 1
     */
    expected_failure_modes: [string, ...string[]];
    /**
     * Scenarios that must pass before deployment.
     *
     * @minItems 1
     */
    required_tests: [string, ...string[]];
    /**
     * How to validate reversibility without production impact.
     */
    simulation_strategy: string;
    /**
     * Conditions for gradual rollout / abort.
     */
    canary_criteria: string;
  };
  executive_brief?: {
    decision: "pilot" | "do_not_pilot" | "needs_redesign";
    /**
     * @minItems 1
     */
    top_risks: [string, ...string[]];
    /**
     * @minItems 1
     */
    must_be_true_before_scale: [string, ...string[]];
    /**
     * @minItems 1
     */
    required_signoffs: [string, ...string[]];
  };
}
